# Generated by Django 5.2.6 on 2025-10-27 15:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lista', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Etiqueta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='contactos',
            name='telefono',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Ingrese un teléfono válido (solo dígitos, opcional +, entre 7 y 15 dígitos).', regex='^\\+?\\d{7,15}$')]),
        ),
        migrations.AddField(
            model_name='contactos',
            name='etiquetas',
            field=models.ManyToManyField(blank=True, related_name='contactos', to='lista.etiqueta'),
        ),
    ]