# Generated by Django 5.2.6 on 2025-12-14 16:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lista', '0002_etiqueta_alter_contactos_telefono_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactos',
            name='correo',
            field=models.EmailField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='contactos',
            name='direccion',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='contactos',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='contactos',
            name='telefono',
            field=models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator(message='Ingrese un teléfono válido (solo dígitos, opcional +, entre 7 y 15 dígitos).', regex='^\\+?\\d{7,15}$')]),
        ),
    ]
